version: "3"

services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    privileged: true
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
